### ISSUE TITLE
using OpenCV to capture webcam frame and send to virtual camera 

### ISSUE THREAD

**Issue by zulfiker** [correaAlex/OBSVirtualCameraOutput#1]
Hi thanks for the project . I have successfully run your sample example. instead of sending  BMP or gif file to virtual camera i am trying to capture webcam frame Opencvsharp library , convert Mat object to Bitmap object and rest of the code is exactly same as yours . this should work in theory . but i am getting this error every time **System.AccessViolationException: 'Attempted to read or write protected memory** on this line `vo_->send(f);`  of  **VirtualOutput.cpp**  file . can you provide feedback if this process is ok or not ? i am attaching the code below 

     `static void Main(string[] args)
        {
            VideoCapture capture = new VideoCapture(0, VideoCaptureAPIs.DSHOW);

            capture.Set(VideoCaptureProperties.FrameWidth, 1280); 
            capture.Set(VideoCaptureProperties.FrameHeight, 720);
            capture.Set(VideoCaptureProperties.FourCC, OpenCvSharp.VideoWriter.FourCC('M', 'J', 'P', 'G'));

            VirtualOutput virtualOutput = new VirtualOutput(1280, 720, 30, FourCC.FOURCC_24BG);

            Mat image = null;
            Mat finalImage = new Mat();
            using (image = new Mat())
            {
                while (true)
                {
                    capture.Read(image);
                    if (image.Empty())
                        break;
                    Cv2.CvtColor(image, finalImage, ColorConversionCodes.BGR2RGB);

                    Bitmap bitmap = finalImage.ToBitmap();

                    ImageConverter converter = new ImageConverter();
                    byte[] imageBytes = (byte[])converter.ConvertTo(bitmap, typeof(byte[]));
                    virtualOutput.Send(imageBytes);

                }
            }`

**Comment by correaAlex** [comment]
Hi, thanks for your feedback. I think the problem is with the FourCC format, its conversions. Try other FourCC formats. If that doesn't help then wait for my PR which would solve the problem

**Comment by correaAlex** [comment]
Hi @zulfiker, use the extension [method](https://github.com/correaAlex/OBSVirtualCameraOutput/tree/master/VirtualCameraOutput.Extensions) (add to dependencies in your project), such as 
```csharp
using OpenCvSharp;
using OpenCvSharp.Extensions;
using System.Drawing;
using VirtualCameraOutput;
using VirtualCameraOutput.Extensions;

namespace Program
{
    class Program
    {
        static void Main(string[] args)
        {
            VideoCapture capture = new VideoCapture(0, VideoCaptureAPIs.DSHOW);

            capture.Set(VideoCaptureProperties.FrameWidth, 1280);
            capture.Set(VideoCaptureProperties.FrameHeight, 720);
            capture.Set(VideoCaptureProperties.FourCC, OpenCvSharp.VideoWriter.FourCC('M', 'J', 'P', 'G'));

            VirtualOutput virtualOutput = new VirtualOutput(1280, 720, 30, FourCC.FOURCC_24BG);
            while (true)
            {
                using (Mat image = new Mat())
                {
                    capture.Read(image);
                    if (image.Empty())
                        break;

                    Bitmap bitmap = image.ToBitmap();
                    virtualOutput.Send(bitmap.ToArray());
                }
            }
        }
    }
}
```

**Comment by zulfiker** [comment]
@correaAlex  thanks for the patch . your solution is very nice . i have made another concise  implementation . this is also working fine. here is that
```
        using (image = new Mat())
         {
             while (true)
              {
                 capture.Read(image);
                  if (image.Empty())
                   break;

                   Cv2.CvtColor(image, finalImage, ColorConversionCodes.BGR2RGB);
                   byte[] imageBytes = finalImage.ImEncode(".bmp");

                  virtualOutput.Send(imageBytes);
                    
              }
         }
```
